# Generated by Django 5.2.3 on 2026-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_course_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
