# Generated by Django 5.2.3 on 2026-04-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
